### ISSUE TITLE
AssertionError assert self.F == self.Fs.max().data[0]

### ISSUE THREAD

**Issue by flyKite1998** [lzhengning/SubdivNet#20]
你好 我在进行manifold数据集上的分类任务训练时，遇到了下面的错误
```
name:  manifold40
Train 0:   0%|                                                                                                                                                                           | 0/2049 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train_cls.py", line 184, in <module>
    train(net, optim, train_dataset, writer, epoch)
  File "train_cls.py", line 33, in train
    mesh_tensor = to_mesh_tensor(meshes)
  File "/mnt/data/wy/SubdivNet/subdivnet/utils.py", line 28, in to_mesh_tensor
    jt.int32(meshes['Fs']))
  File "/mnt/data/wy/SubdivNet/subdivnet/mesh_tensor.py", line 35, in __init__
    assert self.F == self.Fs.max().data[0]
AssertionError
```
我是在ubuntu18.04上用conda搭建环境的，jittor版本1.3.0.14，期待您的答复。

**Comment by lzhengning** [comment]
看了您的结果，`self.Fs.max()` 理论上应该等于 `self.F`，都是 8320，不应该在这里出现 AssertionError。
