### ISSUE TITLE
Data Preprocessing with datagen_maps.py

### ISSUE THREAD

**Issue by saiyudh** [lzhengning/SubdivNet#35]
Hi so I saw the datagen_maps.py being used with the airplane.obj my obj files are in the same format but,
airplane.obj has  Vertices: 252, Faces: 500 and is being converted to Maps to be used by the model.
my._obj_file.obj has  Vertices: 27886, Faces: 55648 
and what is the base_value variable in the code? how do I find the base_value of my obj file? 

while running the code on my obj file, I faced the error : 
Traceback (most recent call last):
  File "datagen_maps.py", line 209, in <module>
    MAPS_demo1()
  File "datagen_maps.py", line 173, in MAPS_demo1
    make_MAPS_shape('Aneurisk_C0009.obj', 'Aneurisk_C0009_MAPS.obj', 200, 3)
  File "datagen_maps.py", line 165, in make_MAPS_shape
    maps = MAPS(mesh.vertices, mesh.faces, base_size=base_size, verbose=True)
  File "/workspace/Storage_fast/SubDivNet/SubdivNet/maps/maps.py", line 361, in __init__
    self.decimate()
  File "/workspace/Storage_fast/SubDivNet/SubdivNet/maps/maps.py", line 380, in decimate
    neighbors = self.base.one_ring_neighbors(i)
  File "/workspace/Storage_fast/SubDivNet/SubdivNet/maps/maps.py", line 53, in one_ring_neighbors
    cycle = nx.cycle_basis(G.subgraph(G[i]))[0]
IndexError: list index out of range

**Comment by zhangai6666** [comment]
Hi saiyudh,

Were you able to resolve the issue? I just came across a similar one. Thanks!
